### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by xstable** [FaridSafi/react-native-gifted-chat#1111]
#### Issue Description
Sine upgrading gifted-chat from 0.4.8 to 0.7.2 I got this Error:

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 61431896 byte allocation with 25165824 free bytes and 53MB until OOM, max allowed footprint 170785432, growth limit 201326592
       at java.lang.StringBuilder.toString(StringBuilder.java:410)
       at android.util.JsonReader.nextString(JsonReader.java:894)
       at android.util.JsonReader.nextValue(JsonReader.java:708)
       at android.util.JsonReader.objectValue(JsonReader.java:691)
       at android.util.JsonReader.peek(JsonReader.java:347)
       at com.facebook.react.devsupport.JSDebuggerWebSocketClient.onMessage(JSDebuggerWebSocketClient.java:187)
       at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:323)
       at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

Logcat throw this in front of crashing the App .. so might be caused of OK-HTTP: 
```
2019-01-29 12:23:44.437 25138-25401/com.myApp I/.myapp: Starting a blocking GC Alloc
2019-01-29 12:23:44.437 25138-25401/com.myApp I/.myapp: Starting a blocking GC Alloc
2019-01-29 12:23:44.531 25138-25401/com.myApp I/.myapp: Clamp target GC heap from 208MB to 192MB
2019-01-29 12:23:44.531 25138-25401/com.myApp I/.myapp: Alloc concurrent copying GC freed 1271(146KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 184MB/192MB, paused 157us total 93.692ms
2019-01-29 12:23:44.531 25138-25401/com.myApp I/.myapp: Starting a blocking GC Alloc
2019-01-29 12:23:44.625 25138-25401/com.myApp I/.myapp: Clamp target GC heap from 208MB to 192MB
2019-01-29 12:23:44.625 25138-25401/com.myApp I/.myapp: Alloc concurrent copying GC freed 84(30KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 184MB/192MB, paused 160us total 93.324ms
2019-01-29 12:23:44.625 25138-25401/com.myApp I/.myapp: Forcing collection of SoftReferences for 117MB allocation
2019-01-29 12:23:44.625 25138-25401/com.myApp I/.myapp: Starting a blocking GC Alloc
2019-01-29 12:23:44.736 25138-25401/com.myApp I/.myapp: Clamp target GC heap from 207MB to 192MB
2019-01-29 12:23:44.736 25138-25401/com.myApp I/.myapp: Alloc concurrent copying GC freed 8176(542KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 183MB/192MB, paused 165us total 110.755ms
2019-01-29 12:23:44.736 25138-25401/com.myApp W/.myapp: Throwing OutOfMemoryError "Failed to allocate a 123161922 byte allocation with 8652528 free bytes and 8MB until OOM, max allowed footprint 201326592, growth limit 201326592"
2019-01-29 12:23:44.736 25138-25401/com.myApp I/.myapp: Starting a blocking GC Alloc
2019-01-29 12:23:44.736 25138-25401/com.myApp I/.myapp: Starting a blocking GC Alloc
2019-01-29 12:23:44.826 25138-25401/com.myApp I/.myapp: Clamp target GC heap from 207MB to 192MB
2019-01-29 12:23:44.826 25138-25401/com.myApp I/.myapp: Alloc concurrent copying GC freed 95(46KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 183MB/192MB, paused 172us total 89.425ms
2019-01-29 12:23:44.826 25138-25401/com.myApp I/.myapp: Starting a blocking GC Alloc
2019-01-29 12:23:44.916 25138-25401/com.myApp I/.myapp: Clamp target GC heap from 207MB to 192MB
2019-01-29 12:23:44.916 25138-25401/com.myApp I/.myapp: Alloc concurrent copying GC freed 65(30KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 183MB/192MB, paused 179us total 89.661ms
2019-01-29 12:23:44.916 25138-25401/com.myApp I/.myapp: Forcing collection of SoftReferences for 117MB allocation
2019-01-29 12:23:44.916 25138-25401/com.myApp I/.myapp: Starting a blocking GC Alloc
2019-01-29 12:23:45.023 12378-12378/? D/KeyguardUpdateMonitor: received broadcast android.intent.action.BATTERY_CHANGED
2019-01-29 12:23:45.024 12378-12378/? D/KeyguardUpdateMonitor: handleBatteryUpdate
2019-01-29 12:23:45.031 25138-25401/com.myApp I/.myapp: Clamp target GC heap from 207MB to 192MB
2019-01-29 12:23:45.031 25138-25401/com.myApp I/.myapp: Alloc concurrent copying GC freed 141(32KB) AllocSpace objects, 0(0B) LOS objects, 4% free, 183MB/192MB, paused 186us total 114.747ms
2019-01-29 12:23:45.031 25138-25401/com.myApp W/.myapp: Throwing OutOfMemoryError "Failed to allocate a 123161928 byte allocation with 8650600 free bytes and 8MB until OOM, max allowed footprint 201326592, growth limit 201326592"
    
    --------- beginning of crash
2019-01-29 12:23:45.034 25138-25401/com.myApp E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.myApp, PID: 25138
    java.lang.OutOfMemoryError: Failed to allocate a 123161928 byte allocation with 8650600 free bytes and 8MB until OOM, max allowed footprint 201326592, growth limit 201326592
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:225)
        at java.lang.StringFactory.newStringFromBytes(StringFactory.java:256)
        at okio.Buffer.readString(Buffer.java:713)
        at okio.Buffer.readUtf8(Buffer.java:684)
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
        at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

#### Expected Results

No OutOfMemory-Error

#### Additional Information

* Nodejs version: 10.14.1
* React version: 16.6.3
* React Native version: 0.57.8
* react-native-gifted-chat version: 0.7.2
* Platform(s) (iOS, Android, or both?): Android

**Comment by xcarpentier** [comment]
Hi,
Sorry about that.
Do you have more information? Like the moment when this occurred: at start chat, when sending or other?
Thanks

**Comment by xstable** [comment]
I mean 0.4.3

It appears after a couple of seconds (30 - 60), after open the chat... but doing nothing inside.
At the moment it seems to work. So I'll have a look at it and report if happend again.

**Comment by xcarpentier** [comment]
Ok so close it. Thanks.
