### ISSUE TITLE
Can't use versions greater than  0.9.11  with 'react-navigation'

### ISSUE THREAD

**Issue by orome** [FaridSafi/react-native-gifted-chat#1448]
#### Issue Description

Can't use versions greater than `~0.9.11` with `react-navigation`.

#### Steps to Reproduce / Code Snippets

Update the version of `react-native-gifted-chat` in `package.json` to more recent versions, e.g., `^0.11.0`.

This results in a series of errors such as 

> Module `react-navigation-stack` does not exist in the Haste module map

Adding these modules to `package.json` removes the error, but then leads to further errors for additional packages.

#### Additional Information

* Nodejs version: 12.11.1
* React version: 16.10.1
* React Native version: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
* react-native-gifted-chat version: (see above)
* Platform(s) (iOS, Android, or both?): iOS
* TypeScript version: 3.6.3

**Comment by troublediehard** [comment]
@orome please share your package.json here

**Comment by orome** [comment]
This is my working 'dependencies' section, before updating `react-navigation`:
```
"dependencies": {
  "expo": "~35.0.0",
  "react": "^16.10.1",
  "react-dom": "^16.10.1",
  "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
  "react-native-web": "^0.11.7",
  "native-base": "^2.13.8",
  "redux": "^4.0.4",
  "react-redux": "^7.1.1",
  "react-navigation": "~3.13.0",
  "react-native-gesture-handler": "^1.4.1",
  "react-native-gifted-chat": "~0.9.11",
  "ibm-watson": "^5.0.0",
  "react-native-fontawesome-pro": "^2.1.0",
  "react-native-svg": "~9.9.2"
},
```

This is my working 'dependencies' section, after updating `react-navigation`:
```
"dependencies": {
  "expo": "~35.0.0",
  "react": "^16.10.1",
  "react-dom": "^16.10.1",
  "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
  "react-native-web": "^0.11.7",
  "native-base": "^2.13.8",
  "redux": "^4.0.4",
  "react-redux": "^7.1.1",
  "react-navigation": "^4.0.10",
  "react-navigation-drawer": "^2.2.2",
  "react-navigation-stack": "^1.9.4",
  "react-navigation-tabs": "^2.5.5",
  "react-native-reanimated": "^1.3.0",
  "react-native-gesture-handler": "^1.4.1",
  "react-native-gifted-chat": "~0.9.11",
  "ibm-watson": "^5.0.0",
  "react-native-fontawesome-pro": "^2.1.0",
  "react-native-svg": "~9.9.2"
},
```
While this works, it isn’t clear why I need to add `react-navigation-stack`, `react-navigation-tabs`, and `react-native-reanimated` when I update `react-navigation` (I understand why I need to `react-navigation-drawer`, since I use it).

If I update Gifted Chat with

    "react-native-gifted-chat": "^0.11.0",

I get:

> Unable to resolve module `react-native-video` from `/Users/Orome/Documents/Projects/Coding/React/enigma/node_modules/react-native-gifted-chat/lib/MessageVideo.js`: Module `react-native-video` does not exist in the Haste module map
> 
> This might be related to https://github.com/facebook/react-native/issues/4968
> To resolve try the following:
>   1. Clear watchman watches: `watchman watch-del-all`.
>   2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
>   3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
>   4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
> 
> ABI34_0_0RCTFatal
> __37-[ABI34_0_0RCTCxxBridge handleError:]_block_invoke
> _dispatch_call_block_and_release
> _dispatch_client_callout
> _dispatch_main_queue_callback_4CF
> __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> __CFRunLoopRun
> CFRunLoopRunSpecific
> GSEventRunModal
> UIApplicationMain
> main
> start
> 0x0

(Note that heeding a warning I get, with our without updating Gifted Chat, `react-native-gesture-handler - expected` and `react-native-reanimated` aren’t the "expected versions" doesn’t change this and in fact results in all kinds of additional unrelated errors.)

**Comment by jbrodriguez** [comment]
I have a similar issue, if I try to install 0.11.x. This is the log

```
⟩ npm i react-native-gifted-chat
npm WARN expo-apple-authentication@1.0.0 requires a peer of @unimodules/core@~3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-apple-authentication@1.0.0 requires a peer of @unimodules/react-native-adapter@~3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-expo@35.0.0 requires a peer of react-native-web@* but none is installed. You must install peer dependencies yourself.
npm WARN react-native-gifted-chat@0.11.0 requires a peer of react-dom@* but none is installed. You must install peer dependencies yourself.

npm ERR! code EPERM
npm ERR! syscall spawn
npm ERR! errno EPERM
npm ERR! Error: spawn EPERM
npm ERR!     at ChildProcess.spawn (internal/child_process.js:394:11)
npm ERR!     at spawn (child_process.js:540:9)
npm ERR!     at execFile (child_process.js:224:17)
npm ERR!     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
npm ERR!     at opts.retry.retries (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24
npm ERR!  OperationalError: spawn EPERM
npm ERR!     at ChildProcess.spawn (internal/child_process.js:394:11)
npm ERR!     at spawn (child_process.js:540:9)
npm ERR!     at execFile (child_process.js:224:17)
npm ERR!     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!     at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
npm ERR!     at opts.retry.retries (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24 {
npm ERR!   cause: Error: spawn EPERM
npm ERR!       at ChildProcess.spawn (internal/child_process.js:394:11)
npm ERR!       at spawn (child_process.js:540:9)
npm ERR!       at execFile (child_process.js:224:17)
npm ERR!       at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
npm ERR!       at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)
npm ERR!       at opts.retry.retries (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)
npm ERR!       at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24 {
npm ERR!     errno: 'EPERM',
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'spawn'
npm ERR!   },
npm ERR!   stack: 'Error: spawn EPERM\n' +
npm ERR!     '    at ChildProcess.spawn (internal/child_process.js:394:11)\n' +
npm ERR!     '    at spawn (child_process.js:540:9)\n' +
npm ERR!     '    at execFile (child_process.js:224:17)\n' +
npm ERR!     '    at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)\n' +
npm ERR!     '    at ret (eval at makeNodePromisifiedEval (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:16:23)\n' +
npm ERR!     '    at opts.retry.retries (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/util/git.js:192:14)\n' +
npm ERR!     '    at /usr/local/lib/node_modules/npm/node_modules/promise-retry/index.js:29:24',
npm ERR!   errno: 'EPERM',
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'spawn'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kayak/.npm/_logs/2019-10-14T13_22_46_286Z-debug.log
```

I'm using  `"react-navigation": "^3.11.1"`, though

This is the log for a successful 0.9.11 install

```
⟩ npm i react-native-gifted-chat@0.9.11

> core-js@2.6.10 postinstall /Volumes/Home/bytelion/argonav-mobile/node_modules/babel-runtime/node_modules/core-js
> node postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN expo-apple-authentication@1.0.0 requires a peer of @unimodules/core@~3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN expo-apple-authentication@1.0.0 requires a peer of @unimodules/react-native-adapter@~3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-expo@35.0.0 requires a peer of react-native-web@* but none is installed. You must install peer dependencies yourself.

+ react-native-gifted-chat@0.9.11
added 19 packages from 62 contributors and audited 924903 packages in 40.72s
found 11 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by jbrodriguez** [comment]
I had this EPERM issue on another project (not Expo) where I'm not using react-native-gifted-chat.

I solved it there by switching to yarn instead of npm.

Not sure if we can ```yarn``` in Expo, but I'll give it a try
