### ISSUE TITLE
Cannot add property user, object is not extensible

### ISSUE THREAD

**Issue by ghasemikasra39** [FaridSafi/react-native-gifted-chat#2155]
#### Issue Description

```bash
vendors~main.chunk.js:74464 Uncaught TypeError: Cannot add property user, object is not extensible
    at MessageContainer.renderRow (vendors~main.chunk.js:74464:19)
    at renderer (vendors~main.chunk.js:103161:18)
    at _ref.<computed> (vendors~main.chunk.js:103185:18)
    at CellRenderer._renderElement (vendors~main.chunk.js:106970:14)
    at CellRenderer.render (vendors~main.chunk.js:106994:24)
    at finishClassComponent (vendors~main.chunk.js:54836:35)
    at updateClassComponent (vendors~main.chunk.js:54789:28)
    at beginWork (vendors~main.chunk.js:56374:20)
    at HTMLUnknownElement.callCallback (vendors~main.chunk.js:41339:18)
    at Object.invokeGuardedCallbackDev (vendors~main.chunk.js:41388:20)
    at invokeGuardedCallback (vendors~main.chunk.js:41448:35)
    at beginWork$1 (vendors~main.chunk.js:61190:11)
    at performUnitOfWork (vendors~main.chunk.js:60026:16)
    at workLoopSync (vendors~main.chunk.js:59963:9)
    at renderRootSync (vendors~main.chunk.js:59929:11)
    at performSyncWorkOnRoot (vendors~main.chunk.js:59546:22)
    at vendors~main.chunk.js:48799:30
    at unstable_runWithPriority (vendors~main.chunk.js:121864:16)
    at runWithPriority$1 (vendors~main.chunk.js:48745:14)
    at flushSyncCallbackQueueImpl (vendors~main.chunk.js:48794:13)
    at flushSyncCallbackQueue (vendors~main.chunk.js:48782:7)
    at scheduleUpdateOnFiber (vendors~main.chunk.js:59146:13)
    at Object.enqueueSetState (vendors~main.chunk.js:49922:9)
    at GiftedChat.push../node_modules/react/cjs/react.development.js.Component.setState (vendors~main.chunk.js:118027:20)
    at GiftedChat.onInitialLayoutViewLayout (vendors~main.chunk.js:73242:12)
    at vendors~main.chunk.js:93353:15
    at vendors~main.chunk.js:89521:7
```

#### Steps to Reproduce / Code Snippets

Just use it normally with this data:
```json
const dummy = [
      {
    "_id": "61f95db6e01853d9f2096d77",
    "user": {
      "_id": "347e92c2-e4f9-4200-95c0-7a3d418a729e",
      "name": "Johnnie",
      "avatar": "https://picsum.photos/200"
    },
    "text": "consectetur amet cillum tempor occaecat nulla excepteur voluptate sit Lorem aliquip qui",
    "createdAt": "1990-12-26T22:48:52.803Z"
  }, {
    "_id": "61f95db6c902fbc5efdecb25",
    "user": {
      "_id": "4ca4534d-3f4f-40f9-a2f5-4e2ee61c722b",
      "name": "Valencia",
      "avatar": "https://picsum.photos/200"
    },
    "text": "sunt veniam duis sint cillum ut consequat aute nulla pariatur consectetur velit",
    "createdAt": "2010-07-15T19:23:54.930Z"
  }, {
    "_id": "61f95db60e5bd20ec0db8dce",
    "user": {
      "_id": "d1674831-c6dd-4200-8017-307abbc6cecb",
      "name": "Alexander",
      "avatar": "https://picsum.photos/200"
    },
    "text": "consequat sint",
    "createdAt": "2008-06-04T11:53:07.277Z"
  }, {
    "_id": "61f95db6e05c3f9e169568e8",
    "user": {
      "_id": "152a5a6d-b242-4396-ada4-1b2829d11f51",
      "name": "Lacey",
      "avatar": "https://picsum.photos/200"
    },
    "text": "eiusmod",
    "createdAt": "1983-03-09T06:56:33.463Z"
  }, {
    "_id": "61f95db6285f77e0cd6b1690",
    "user": {
      "_id": "702f1ed8-c511-48c1-a4b4-4b032d7b926f",
      "name": "Bettye",
      "avatar": "https://picsum.photos/200"
    },
    "text": "in",
    "createdAt": "1982-07-11T02:49:06.016Z"
  }, {
    "_id": "61f95db630905a4bc55fbc94",
    "user": {
      "_id": "64eedcea-258e-400c-a952-d7b9240f92ce",
      "name": "Ruthie",
      "avatar": "https://picsum.photos/200"
    },
    "text": "tempor ut tempor consectetur",
    "createdAt": "1972-02-22T04:58:58.413Z"
  }, {
    "_id": "61f95db6dfd0d8883d0fc430",
    "user": {
      "_id": "f5085d97-0175-41ee-86c3-edbeadfd8c80",
      "name": "Eddie",
      "avatar": "https://picsum.photos/200"
    },
    "image": "https://picsum.photos/200",
    "createdAt": "2021-11-29T01:39:17.447Z"
  }, {
    "_id": "61f95db63da6f9a53a11fc5a",
    "user": {
      "_id": "d6e8281a-fe10-48c7-8ea9-0ea5cb8357cb",
      "name": "Stafford",
      "avatar": "https://picsum.photos/200"
    },
    "image": "https://picsum.photos/200",
    "createdAt": "1973-08-19T23:53:56.916Z"
  }, {
    "_id": "61f95db6e7ab0054b6896e8c",
    "text": "a user with name Sandoval joined",
    "createdAt": "1986-05-24T16:18:02.374Z",
    "system": true
  }, {
    "_id": "61f95db6e1fa4b30b511bc33",
    "text": "a note with id 61f95db6e1fa4b30b511bc33 has been found",
    "createdAt": "2003-12-28T07:31:44.261Z",
    "system": true
  }, {
    "_id": "61f95db6a8b3755af16135e7",
    "text": "a note with id 61f95db6a8b3755af16135e7 has been found",
    "createdAt": "1995-03-02T09:45:25.006Z",
    "system": true
  }, {
    "_id": "61f95db64f70c5f77e55e7b2",
    "text": "a note with id 61f95db64f70c5f77e55e7b2 has been found",
    "createdAt": "1996-07-06T01:19:13.922Z",
    "system": true
  }]
```

#### Expected Results

Don't get any error

#### Additional Information

* Nodejs version: v16.0.0
* React version: [FILL THIS OUT]
* react-native-web version:  "^0.17.5"
* react-native-gifted-chat version: "^0.16.3"
* Platform(s) (iOS, Android, or both?): web
* TypeScript version: "^4.5.2"

**Comment by Yogesh-Dubey-0804** [comment]
it works fine

**Comment by codlab** [comment]
```
            if (!item.user) {
                if (!item.system) {
                    warning('GiftedChat: `user` is missing for message', JSON.stringify(item));
                }
                item.user = { _id: 0 };
            }
```

This piece of code in the `renderRow` method is responsible for this issue. Since the item is from the data gotten from the props, it can't be written to.

To prevent the issue, set for each messages you are sending to the props at least one instance of user (`{ _id: 0 }`)
