### ISSUE TITLE
IN MYSQL WHEN I RUN NODEMON APP THIS ERROR WILL SHOW PLEASE HELP

### ISSUE THREAD

**Issue by mamonaabdullah122** [FaridSafi/react-native-gifted-chat#2238]
throw err; // Rethrow non-MySQL errors
      ^

TypeError: Cannot read properties of undefined (reading 'insertId')
    at Query.<anonymous> (/Volumes/Os/Project/server/dbService.js:53:36)
    at Query.<anonymous> (/Volumes/Os/Project/server/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/Volumes/Os/Project/server/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/Volumes/Os/Project/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/Volumes/Os/Project/server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/Volumes/Os/Project/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Volumes/Os/Project/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Volumes/Os/Project/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Volumes/Os/Project/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Volumes/Os/Project/server/node_modules/mysql/lib/Connection.js:88:28)

**Comment by mamonaabdullah122** [comment]
Help!!!

**Comment by mariomurrent-softwaresolutions** [comment]
The error is in the first line of your output:

_TypeError: Cannot read properties of undefined (reading 'insertId')_

**Comment by kesha-antonov** [comment]
Not related to this lib

**Comment by mariomurrent-softwaresolutions** [comment]
I guess this is not related to this library,
