### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'showActionSheetWithOptions')

### ISSUE THREAD

**Issue by kovkev** [FaridSafi/react-native-gifted-chat#2294]
#### Issue Description

With react-native-web. When I click and hold on a message, I get 

```
Uncaught TypeError: Cannot read properties of undefined (reading 'showActionSheetWithOptions')
    at Bubble._this.onLongPress (Bubble.tsx:266:1)
    at PressResponder._performTransitionSideEffects (PressResponder.js:426:1)
    at PressResponder._receiveSignal (PressResponder.js:397:1)
    at PressResponder._handleLongPress (PressResponder.js:509:1)
    at PressResponder.js:219:1
```

#### Steps to Reproduce / Code Snippets

Use `<GiftedChat/>`

#### Expected Results

A menu pops up

#### Additional Information

* Nodejs version: 19.0.0
* React version: 18.0.0
* React Native version: 0.69.6
* react-native-gifted-chat version: 1.0.3/1.0.4
* Platform(s) (iOS, Android, or both?): Web
* TypeScript version: 4.3.5

**Comment by bradbyte** [comment]
This has been fixed in @expo/react-native-action-sheet 4.0.1.
