### ISSUE TITLE
Gifted Chat Playground is not working

### ISSUE THREAD

**Issue by qi-xia** [FaridSafi/react-native-gifted-chat#2320]
Gifted Chat Playground is not working, below is the error message

Unable to resolve module '@unimodules/core.js'
  Evaluating @unimodules/core.js
  Evaluating expo-av.js
  Evaluating App.tsx.js
  Loading App.tsx
Error: Unable to resolve module '@unimodules/core.js'
    at Object.eval (@unimodules/core.js:1:1

    at eval (@unimodules/core.js

    at eval (@unimodules/core.js

    at eval (<anonymous>)
    at [snack internals]
    at Module.o ([snack internals]
    at e.evaluate ([snack internals]
    at Ze ([snack internals]
    at [snack internals]
    at https://snack-web-player.s3.us-west-1.amazonaws.com/v2/46/static/js/app.e3f1aedc.chunk.js:1:30706

**Comment by kesha-antonov** [comment]
Fixed in master
